### ISSUE TITLE
Ensure Python2 compliance

### ISSUE THREAD

**Issue by awwad** [awwad/uptanedemo#13]
Scan for anything that breaks in Python2: possibly the XMLRPC listening code in the demo (and that may currently still exist in the reference implementation's director code - which must still be stripped out).

This is because the ASN.1 encoders (which depend on PyASN) might require Python2.

**Comment by lukpueh** [comment]
I'm on it.

**Comment by awwad** [comment]
Resolved and merged by PR #23. Thanks, Lukas!
