### ISSUE TITLE
Demo: Library required to play sounds?

### ISSUE THREAD

**Issue by vladimir-v-diaz** [awwad/uptanedemo#37]
Should we instruct users to install a library to play sounds?  I am running Ubuntu and got the following error when the demo code tried to play a sound clip:

```Python
The Director has instructed us to download a file that does  does not exactly match the Image Repository metadata. File:            
                                                                  '/file5.txt'                                                                  
No player found on this platform.
[2017.03.08 17:41:44UTC] [primary] INFO [primary.py:primary_update_cycle():484]
Metadata for the following Targets has been validated by both the Director and the OEM repository. They will now be downloaded:[]

Submitting the Primary's manifest to the Director.
Submission of Vehicle Manifest complete.
```

**Comment by awwad** [comment]
Sure. The sound code works on both an OS X laptop and a Raspberry Pi running Raspbian, so I'm somewhat surprised that your Ubuntu install doesn't just work. I haven't looked closely at the dependencies for demo flair.

It would be good to check that out and add a note along the lines of to-play-sound-install-this, or maybe just if-you-don't-have-sound-in-the-demo-install-this.

**Comment by awwad** [comment]
This issue was moved to uptane/uptane#25
