### ISSUE TITLE
Run cleanup routine after running the demo scripts

### ISSUE THREAD

**Issue by vladimir-v-diaz** [awwad/uptanedemo#38]
Adjust the `demo_director` and `demo_oem_repo` modules to do cleanup of the Popen'd processes when exited so that the user doesn't have to manually call `kill_server()`.

Temporary files should also be deleted after running the demo scripts.  For example, the following temp files remain on disk after running the demo:

```
	demo/pinned.json_primary_8K6oY
	demo/pinned.json_primary_xRpyU
	demo/pinned.json_secondary_Q14hh
	director/
	file5.txt
	mainrepo/
        temp_primaryl0lQv
        temp_secondaryLgE55
        temp_primaryWNouY
```

**Comment by awwad** [comment]
This issue was moved to uptane/uptane#24
